### PR TITLE
Swagger documentation

### PR DESCRIPTION
**Pull request by mrrys00**
Please provide me with info if you like to have swagger docs for our services

Pros:
- shorter than 5 min per service
- looks good

No cons :smile:

### CODE REVIEW

**Comment by matthewcga** [comment]
yup

**Comment by mrrys00** [comment]
OK, imo the best idea is to use Swagger docs for both services with the docker compose. The interactive documentation is provided with the container and exposed at the specified localhost port (for now 8084 for Go and 8081 for Py). I've added my last fixes so please review and, if you agree with the changes and don't have any comments, merge (with the commit squash)

**Review by mrrys00 — COMMENTED** [review]
Self review OK, waiting for other reviews

**Comment by mrrys00** [comment]
These commits were merged by @matthewcga to the PR #5 so there is no reason to review that here, PR #4 closed

**Pull request closed without merging**
